x-remote-dev-base: &remote
  image: remote-build-dev:latest
  working_dir: /app
  env_file:
    - ../cmd/remote/env/.env.local
  volumes:
    - ../cmd/remote:/app/cmd/remote
    - /app/cmd/remote/env # exclude env files
    - ../cmd/remote/env/.env:/app/cmd/remote/env/.env
    - ../internal/api/remote:/app/internal/api/remote
    - ../internal/vars/remote:/app/internal/vars/remote
    - ../pkg:/app/pkg
    - ../docker/.air-remote-docker.toml:/app/.air-remote-docker.toml

x-front-dev-base: &front
  image: front-build-dev:latest
  volumes:
    - ../web:/app
    - /app/node_modules

services:
  server-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile-server.dev
    container_name: server-dev
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/server/env/.env.local
    environment:
      - APP_PORT=8080
      - APP_NAME=Development Server
    volumes:
      - ../cmd/server/main.go:/app/cmd/server/main.go
      - ../cmd/server/app.go:/app/cmd/server/app.go
      - /app/cmd/server/env # exclide env files
      - ../cmd/server/env/.env:/app/cmd/server/env/.env
      - ../internal/api/server:/app/internal/api/server
      - ../internal/vars/server:/app/internal/vars/server
      - ../pkg:/app/pkg
      - ../docker/.air-server-docker.toml:/app/.air-server-docker.toml

  remote-dev-1:
    <<: *remote
    container_name: remote-1-dev
    environment:
      - APP_PORT=8081
      - APP_NAME=Development Remote-1
    ports:
      - "8081:8081"

  remote-dev-2:
    <<: *remote
    container_name: remote-2-dev
    environment:
      - APP_PORT=8082
      - APP_NAME=Development Remote-2
    ports:
      - "8082:8082"

  server-front-dev:
    <<: *front
    container_name: server-front-dev
    ports:
      - "3000:3000"
    command: >
      sh -c "pnpm install && pnpm --filter ./apps/server dev"
    environment:
      - VITE_FRONT_PORT=3000
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - server-dev

  remote-front-dev-1:
    <<: *front
    container_name: remote-front-1-dev
    ports:
      - "3001:3001"
    command: >
      sh -c "pnpm install && pnpm --filter remote dev"
    environment:
      - VITE_FRONT_PORT=3001
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - remote-dev-1

  remote-front-dev-2:
    <<: *front
    container_name: remote-front-2-dev
    ports:
      - "3002:3002"
    command: >
      sh -c "pnpm install && pnpm --filter remote dev"
    environment:
      - VITE_FRONT_PORT=3002
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - remote-dev-2

  # hub:
  #   image: nats:latest
  #   container_name: nats-hub
  #   ports:
  #     - "4222:4222"     # hub client port
  #     - "8222:8222"     # hub monitoring
  #     - "7422:7422"     # leafnode port
  #   volumes:
  #     - ./hub.conf:/etc/nats/hub.conf:ro
  #     - hub-js:/data/jetstream
  #   command: ["-c", "/etc/nats/hub.conf"]

  # leaf1:
  #   image: nats:latest
  #   container_name: nats-leaf1
  #   ports:
  #     - "4223:4222"     # leaf client port
  #     - "8223:8222"     # leaf monitoring
  #   volumes:
  #     - ./leaf1.conf:/etc/nats/leaf.conf:ro
  #     - leaf-js1:/data/jetstream
  #   command: ["-c", "/etc/nats/leaf.conf"]
  #   depends_on:
  #     - hub

  # leaf2:
  #   image: nats:latest
  #   container_name: nats-leaf2
  #   ports:
  #     - "4224:4222"     # leaf client port
  #     - "8224:8222"     # leaf monitoring
  #   volumes:
  #     - ./leaf2.conf:/etc/nats/leaf.conf:ro
  #     - leaf-js2:/data/jetstream
  #   command: ["-c", "/etc/nats/leaf.conf"]
  #   depends_on:
  #     - hub

volumes:
  hub-js:
  leaf-js1:
  leaf-js2:
