FROM golang:1.26-alpine AS builder
WORKDIR /app

# Cache deps
COPY go.mod go.sum ./
RUN go mod download

# copy only
COPY cmd/central/*.go cmd/central/
COPY internal internal
COPY pkg pkg

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o main ./cmd/central

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/main .
CMD ["./main"]