x-back-remote-dev-base: &back-remote
  image: back-remote-dev-build:latest
  working_dir: /app
  env_file:
    - ../cmd/remote/env/.env.local
  volumes:
    - ../cmd/remote:/app/cmd/remote
    - /app/cmd/remote/env # exclude env files
    - ../cmd/remote/env/.env:/app/cmd/remote/env/.env
    - ../internal/api/remote:/app/internal/api/remote
    - ../internal/vars/remote:/app/internal/vars/remote
    - ../pkg:/app/pkg
    - ../docker/.air-remote-docker.toml:/app/.air-remote-docker.toml
      - ../internal/embed:/app/internal/embed

x-front-dev-base: &front
  image: front-dev-build:latest
  volumes:
    - ../web:/app
    - /app/node_modules

services:
  back-central-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile-backend-central.dev
    container_name: back-central-dev
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/central/env/.env.local
    environment:
      - APP_PORT=8080
      - APP_NAME=Development Central
    volumes:
      - ../cmd/central/main.go:/app/cmd/central/main.go
      - ../cmd/central/app.go:/app/cmd/central/app.go
      - /app/cmd/central/env # exclide env files
      - ../cmd/central/env/.env:/app/cmd/central/env/.env
      - ../internal/api/central:/app/internal/api/central
      - ../internal/vars/central:/app/internal/vars/central
      - ../pkg:/app/pkg
      # FIXME remove ../docker
      - ../docker/.air-central-docker.toml:/app/.air-central-docker.toml
      - ../internal/embed:/app/internal/embed

  # back-remote-dev-1:
  #   <<: *back-remote
  #   container_name: back-remote-dev-1
  #   environment:
  #     - APP_PORT=8081
  #     - APP_NAME=Development Remote-1
  #   ports:
  #     - "8081:8081"

  # back-remote-dev-2:
  #   <<: *back-remote
  #   container_name: back-remote-dev-2
  #   environment:
  #     - APP_PORT=8082
  #     - APP_NAME=Development Remote-2
  #   ports:
  #     - "8082:8082"

  front-central-dev:
    <<: *front
    container_name: front-central-dev
    ports:
      - "3000:3000"
    command: >
      sh -c "pnpm install && pnpm --filter ./apps/central dev"
    environment:
      - VITE_FRONT_PORT=3000
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://back-central-dev:8080 # used in vite proxy
    depends_on:
      - back-central-dev

  # front-remote-dev-1:
  #   <<: *front
  #   container_name: front-remote-dev-1
  #   ports:
  #     - "3001:3001"
  #   command: >
  #     sh -c "pnpm install && pnpm --filter remote dev"
  #   environment:
  #     - VITE_FRONT_PORT=3001
  #     - CI=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #   depends_on:
  #     - back-remote-dev-1

  # front-remote-dev-2:
  #   <<: *front
  #   container_name: front-remote-dev-2
  #   ports:
  #     - "3002:3002"
  #   command: >
  #     sh -c "pnpm install && pnpm --filter remote dev"
  #   environment:
  #     - VITE_FRONT_PORT=3002
  #     - CI=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  #   depends_on:
  #     - back-remote-dev-2

  # hub:
  #   image: nats:latest
  #   container_name: nats-hub
  #   ports:
  #     - "4222:4222"     # hub client port
  #     - "8222:8222"     # hub monitoring
  #     - "7422:7422"     # leafnode port
  #   volumes:
  #     - ./hub.conf:/etc/nats/hub.conf:ro
  #     - hub-js:/data/jetstream
  #   command: ["-c", "/etc/nats/hub.conf"]

  # leaf1:
  #   image: nats:latest
  #   container_name: nats-leaf1
  #   ports:
  #     - "4223:4222"     # leaf client port
  #     - "8223:8222"     # leaf monitoring
  #   volumes:
  #     - ./leaf1.conf:/etc/nats/leaf.conf:ro
  #     - leaf-js1:/data/jetstream
  #   command: ["-c", "/etc/nats/leaf.conf"]
  #   depends_on:
  #     - hub

  # leaf2:
  #   image: nats:latest
  #   container_name: nats-leaf2
  #   ports:
  #     - "4224:4222"     # leaf client port
  #     - "8224:8222"     # leaf monitoring
  #   volumes:
  #     - ./leaf2.conf:/etc/nats/leaf.conf:ro
  #     - leaf-js2:/data/jetstream
  #   command: ["-c", "/etc/nats/leaf.conf"]
  #   depends_on:
  #     - hub

volumes:
  hub-js:
  leaf-js1:
  leaf-js2:
