services:
  back-remote-build:
    build:
      context: ..
      dockerfile: docker/Dockerfile-backend-remote.dev
    image: back-remote-dev-build:latest

  front-build:
    build:
      context: ../web
      dockerfile: ../docker/Dockerfile.frontend.dev
    image: front-dev-build:latest
