services:
  remote-build:
    build:
      context: ..
      dockerfile: docker/Dockerfile-remote.dev
    image: remote-build-dev:latest

  front-build:
    build:
      context: ../web
      dockerfile: ../docker/Dockerfile.frontend.dev
    image: front-build-dev:latest
