x-remote-base: &remote
  build:
    context: ..
    dockerfile: docker/Dockerfile-remote.prod
  working_dir: /app
  env_file:
    - ../cmd/remote/env/.env
    - ../cmd/remote/env/.env.local

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile-server.prod
    container_name: server-prod
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/server/env/.env
      - ../cmd/server/env/.env.local
    environment:
      - APP_PORT=8080
      - APP_NAME=Production Server

  remote-1:
    <<: *remote
    container_name: remote-1-prod
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - APP_NAME=Production Remote-1

  remote-2:
    <<: *remote
    container_name: remote-2-prod
    ports:
      - "8082:8082"
    environment:
      - APP_PORT=8082
      - APP_NAME=Production Remote-2

  # hub:
  #   image: nats:latest
  #   container_name: nats-hub
  #   ports:
  #     - "4222:4222"     # hub client port
  #     - "8222:8222"     # hub monitoring
  #     - "7422:7422"     # leafnode port
  #   volumes:
  #     - ./hub.conf:/etc/nats/hub.conf:ro
  #     - hub-js:/data/jetstream
  #   command: ["-c", "/etc/nats/hub.conf"]

  # leaf1:
  #   image: nats:latest
  #   container_name: nats-leaf1
  #   ports:
  #     - "4223:4222"     # leaf client port
  #     - "8223:8222"     # leaf monitoring
  #   volumes:
  #     - ./leaf1.conf:/etc/nats/leaf.conf:ro
  #     - leaf-js1:/data/jetstream
  #   command: ["-c", "/etc/nats/leaf.conf"]
  #   depends_on:
  #     - hub

  # leaf2:
  #   image: nats:latest
  #   container_name: nats-leaf2
  #   ports:
  #     - "4224:4222"     # leaf client port
  #     - "8224:8222"     # leaf monitoring
  #   volumes:
  #     - ./leaf2.conf:/etc/nats/leaf.conf:ro
  #     - leaf-js2:/data/jetstream
  #   command: ["-c", "/etc/nats/leaf.conf"]
  #   depends_on:
  #     - hub
  

volumes:
  hub-js:     # for nats streaming server
