FROM golang:1.26-alpine

WORKDIR /app

# Needed tools
RUN apk add --no-cache git bash
RUN go install github.com/air-verse/air@latest

# Copy go modules first (better caching)
COPY go.mod go.sum ./
RUN go mod download

# WORKDIR /app/cmd/remote
WORKDIR /app

CMD ["air", "-c", "/app/.air-remote-docker.toml"]