port: 4222
server_name: hub-central

jetstream {
  store_dir: /data/jetstream
  max_mem_store: 1Gb
  max_file_store: 10Gb
}

debug: true
trace: true
http_port: 8222

leafnodes {
  port: 7422
}

accounts {
  LEAF_ACCT {
    # Define the NKey directly inside the account.
    # The NATS parser natively supports the 'nkey' field here.
    users = [
      { nkey: "UCEUFADTOMI4LGULTLWARFVYRSTCRSZ456Q5BXFSEY2VT6EAJZSXCTH4" },
      { nkey: "UAAEW6S6YKM725ZQX2ENLUB2433K6AVOE2TELVJJ4SBDJ5EYYSEMGORA" },
      { nkey: "UAUIAYYHX2S23O4ZJAPBHG4DCFRIBSUMZ36W3DS6RZQTOAXORP35QEJG" }
    ]
    exports = [{ service: ">" }]
  }
  SYS {}
}

system_account: SYS