port: 4222
http_port: 8222
server_name: hub-central
debug: true
trace: true

jetstream {
  store_dir: /data/jetstream
  max_mem_store: 1Gb
  max_file_store: 10Gb
  domain: "hub"
}

leafnodes {
  port: 7422
}

accounts {
  LEAF_1 {
    users = [
      { 
        nkey: "UAI5XOQWJPSXVEDUKE32F5IMTF2HJE5VPE4OWG4GH5MMGYXALFEMEYW3" 
        permissions = {
          publish = ["from.leaf1.>"]
          subscribe = ["to.leaf1.>"]
        }
      }
    ]
    imports = [
      { stream: { account: CENTRAL, subject: "to.leaf1.>" } }
    ]
    exports = [
      { stream: "from.leaf1.>" }
    ]
  }

  LEAF_2 {
    users = [
      { 
        nkey: "UA3ZSLVATNMOU6VC6MQVS3JVGE4TQSLDFBP4VPU3SZZPDD62XQ4N4E67" 
        permissions = {
          publish = ["from.leaf2.>"]
          subscribe = ["to.leaf2.>"]
        }
      }
    ]
    imports = [
      { stream: { account: CENTRAL, subject: "to.leaf2.>" } }
    ]
    exports = [
      { stream: "from.leaf2.>" }
    ]
  }

  CENTRAL {
    jetstream: enabled
    
    users = [
      { nkey: "UAU3SRHJ7MNRPXDNDJSWDIOC55CO2TICF4GWMNZ4K6YGD6ZL6RIYJ6YJ" }
    ]
    exports = [
      # { stream: "to.leaf1.>" }
      # { stream: "to.leaf2.>" }
      { stream: "to.>" }
    ]
    imports = [
      { stream: { account: LEAF_1, subject: "from.leaf1.>" } }
      { stream: { account: LEAF_2, subject: "from.leaf2.>" } }
    ]
  }

  SYS {}
}

system_account: SYS