port: 4222
server_name: nats-leaf2
http_port: 8222
debug: true
trace: true

jetstream {
  store_dir: /data/jetstream
  max_mem_store: 1Gb
  max_file_store: 10Gb
  domain: "leaf2"
}

leafnodes {
  remotes = [
    {
      url: "nats-leaf://nats-hub:7422"
      nkey: "SUAE5XYGJT44ZGEBNBP6RJF5LPE4JJZS2DR5JI2ZVKX2ZZC26IHIKHNYFY"
      
      # IMPORTANT: Tell the leaf node to bridge your LOCAL account traffic over this remote connection.
      account: "LOCAL"
    }
  ]
}

accounts {
  LOCAL {
    users = [
      { nkey: "UAQTM4SCVQBGBHJMJYVVRDKPOUN5F766UCIYH5YFOXPLCHXNTY23VWEN" }
    ]
  }
}