# nats-server.conf
port: 4222
server_name: nats-leaf2          # Helpful for monitoring

# Enable JetStream
jetstream {
  store_dir: /data/jetstream
  max_mem_store: 1Gb
  max_file_store: 10Gb
  domain: "leaf2"
}

debug: true
trace: true
http_port: 8222

leafnodes {
  remotes = [
    {
      url: "nats-leaf://nats-hub:7422"
      nkey: "SUAGLCPNMJQWPIOZEVWHG2DTGHPUGLL6LS3WZ3MXETLSF2YYYZI54OJNZY"
      
      # IMPORTANT: Tell the leaf node to bridge your LOCAL account 
      # traffic over this remote connection.
      account: "LOCAL"
    }
  ]
}

accounts {
  LOCAL {
    users = [
      { user: "localapp", password: "secret" }
    ]
  }
}
