port: 4222
server_name: nats-leaf1

jetstream {
  store_dir: /data/jetstream
  max_mem_store: 1Gb
  max_file_store: 10Gb
  domain: "leaf1"
}

debug: true
trace: true
http_port: 8222

leafnodes {
  remotes = [
    {
      url: "nats-leaf://nats-hub:7422"
      # nkey: "SUAF2DU5LB6KQCLAHXTPCXAQNHHJVM2QQNXVH2NFL72S44I7TJGO5HSA5M"
      nkey: "SUAJMOCWXXCQHRMXPUBBBI22IAQNQHDW5HG6CBHFNMFF6SRKPNFH7CQ4KQ"
      
      # IMPORTANT: Tell the leaf node to bridge your LOCAL account 
      # traffic over this remote connection.
      account: "LOCAL"
    }
  ]
}

accounts {
  LOCAL {
    users = [
      { user: "localapp", password: "secret" }
    ]
  }
}