openapi: 3.0.0
info:
  title: Report-Engine Remote Service
  version: 0.0.0
tags:
  - name: ping
paths:
  /api/ping:
    get:
      operationId: ping_pong
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharedModels.PingResponse'
      tags:
        - ping
components:
  schemas:
    SharedModels.PingResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
servers:
  - url: http://localhost:8081
    description: Report-Engine API (Remote)
    variables: {}
