@baseUrl_HUB = http://localhost:8222
@baseUrl_LEAF1 = http://localhost:8223


# TODO secure NATS monitoring endpoint

### HUB LeafNodes Connections
{{baseUrl_HUB}}/leafz

### Leaf1 LeafNodes Connections
{{baseUrl_LEAF1}}/leafz

